[package]
name = "semantic-sdp"
version = "0.1.0"
authors = ["Asher Baker <asherkin@limetech.io>"]
edition = "2018"

[dependencies]
nom = "6"
ordered-multimap = "0.3"
semantic-sdp-derive = { version = "0.1", path = "semantic-sdp-derive" }

[dev-dependencies]
paste = "1"
